name: bego_ovino_caprino
description: Sistema de GestÃ£o para Ovinocultura e Caprinocultura

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  uuid: ^4.5.0
  supabase_flutter: ^2.3.4
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  sqflite: ^2.3.0
  sqflite_common: ^2.5.4
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  supabase: ^2.3.4
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
